name: Build All Platforms

on:
  workflow_dispatch:

jobs:
  linux:
    uses: ./.github/workflows/build-linux64.yml

  windows:
    uses: ./.github/workflows/build-windows-macosx.yml

  switch:
    uses: ./.github/workflows/build-switch.yml
